apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
