apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
#  annotations:
#    metallb.universe.tf/loadBalancerIPs: 192.168.1.10
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
